splash = false
preload = $XDG_CONFIG_HOME/omarchy/current/theme/backgrounds/blade-runner-1.jpg
preload = $XDG_CONFIG_HOME/omarchy/current/theme/backgrounds/blade-runner-2.jpg
preload = $XDG_CONFIG_HOME/omarchy/current/theme/backgrounds/blade-runner-3.jpg
preload = $XDG_CONFIG_HOME/omarchy/current/theme/backgrounds/blade-runner-4.jpg
preload = $XDG_CONFIG_HOME/omarchy/current/theme/backgrounds/blade-runner-5.jpg
preload = $XDG_CONFIG_HOME/omarchy/current/theme/backgrounds/blade-runner-6.jpg
preload = $XDG_CONFIG_HOME/omarchy/current/theme/backgrounds/blade-runner-7.jpg
preload = $XDG_CONFIG_HOME/omarchy/current/theme/backgrounds/blade-runner-8.jpg
preload = $XDG_CONFIG_HOME/omarchy/current/theme/backgrounds/blade-runner-9.jpg
