console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[transient_prompt]
  newline = true
  background = 'transparent'
  foreground = 'red'
  template = '❱ '

[secondary_prompt]
  background = 'transparent'
  foreground = 'red'
  template = '<lightYellow>╰─</>❱ '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'lightYellow'
    template = '╭─ {{ .UserName }}'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'lightYellow'
    template = '── {{ .PWD }}'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'lightYellow'
    template = '──{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uF044 {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uF046 {{ .Staging.String }}{{ end }}'

    [blocks.segments.properties]
      branch_icon = ' '

[[blocks]]
  type = 'prompt'
  newline = true
  alignment = 'left'

  [[blocks.segments]]
    type = 'status'
    foreground = 'magenta'
    template = '<lightYellow>├─</> {{ reason .Code }}'

    
[[blocks]]
  type = 'prompt'
  newline = true
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    foreground = 'red'
    template = '<lightYellow>╰─</><green>❱</><lightRed>❱</>❱'

