console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[transient_prompt]
  newline = true
  background = 'transparent'
  foreground = 'red'
  template = '❱ '

[secondary_prompt]
  background = 'transparent'
  foreground = 'yellow'
  template = '╰─<red>❱</> '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    background = 'lightYellow'
    foreground = 'transparent'
    style = 'diamond'
    leading_diamond = '<yellow,transparent>╭──</>'
    trailing_diamond = '<yellow,transparent></>'
    template = ' {{ .UserName }}'

  [[blocks.segments]]
    type = 'path'
    background = 'lightYellow'
    foreground = 'transparent'
    style = 'diamond'
    leading_diamond = '<yellow,transparent>──</>'
    trailing_diamond = '<yellow,transparent></>'
    template = ' {{ .PWD }}'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    background = 'lightYellow'
    foreground = 'transparent'
    style = 'diamond'
    leading_diamond = '<yellow,transparent>──</>'
    trailing_diamond = '<yellow,transparent></>'
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} \uF044 {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }} \uF046 {{ .Staging.String }}{{ end }}'

    [blocks.segments.properties]
      branch_icon = ''

  [[blocks.segments]]
    type = 'status'
    background = 'magenta'
    foreground = 'white'
    style = 'diamond'
    leading_diamond = '<yellow,transparent>──</>'
    trailing_diamond = '<yellow,transparent></>'
    template = ' {{ reason .Code }}'

[[blocks]]
  type = 'prompt'
  newline = true
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    foreground = 'yellow'
    template = '│'
    
[[blocks]]
  type = 'prompt'
  newline = true
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    foreground = 'yellow'
    template = '╰──</><green>❱</><lightRed>❱</><red>❱</>'

